/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * KizunaShelf API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

export const getHealthResponseEntityCountMin = 0;

export const getHealthResponseRelationCountMin = 0;



export const GetHealthResponse = zod.object({
  "ok": zod.boolean(),
  "generatedAt": zod.string(),
  "entityCount": zod.number().min(getHealthResponseEntityCountMin),
  "relationCount": zod.number().min(getHealthResponseRelationCountMin)
})


export const getConfigResponseHomeOneSectionsItemLimitMin = 0;



export const GetConfigResponse = zod.object({
  "taxonomyRoot": zod.string(),
  "home": zod.union([zod.object({
  "title": zod.string().nullish(),
  "sections": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "type": zod.string(),
  "status": zod.union([zod.union([zod.string(),zod.array(zod.string())]),zod.null()]).optional(),
  "limit": zod.number().min(getConfigResponseHomeOneSectionsItemLimitMin).nullish(),
  "sort": zod.string().nullish(),
  "direction": zod.union([zod.enum(['asc', 'desc']),zod.null()]).optional()
})).optional()
}),zod.null()]).optional(),
  "types": zod.array(zod.object({
  "id": zod.string(),
  "label": zod.string(),
  "path": zod.string()
}))
})


export const getHomeResponseSectionsItemLimitMin = 0;

export const getHomeResponseSectionsItemTotalMin = 0;

export const getHomeResponseSectionsItemItemsItemRelationCountMin = 0;



export const GetHomeResponse = zod.object({
  "generatedAt": zod.string(),
  "title": zod.string(),
  "sections": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "status": zod.array(zod.string()),
  "limit": zod.number().min(getHomeResponseSectionsItemLimitMin),
  "sort": zod.string(),
  "direction": zod.string(),
  "total": zod.number().min(getHomeResponseSectionsItemTotalMin),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getHomeResponseSectionsItemItemsItemRelationCountMin)
}))
}))
})


export const GetStatsQueryParams = zod.object({
  "type": zod.string().optional()
})

export const getStatsResponseTotalMin = 0;

export const getStatsResponseRelationsMin = 0;

export const getStatsResponseByTypeItemCountMin = 0;

export const getStatsResponseByStatusItemCountMin = 0;

export const getStatsResponseTopRelationsItemRelationCountMin = 0;



export const GetStatsResponse = zod.object({
  "generatedAt": zod.string(),
  "total": zod.number().min(getStatsResponseTotalMin),
  "relations": zod.number().min(getStatsResponseRelationsMin),
  "byType": zod.array(zod.object({
  "id": zod.string(),
  "label": zod.string(),
  "count": zod.number().min(getStatsResponseByTypeItemCountMin)
})),
  "dateFields": zod.array(zod.string()),
  "byStatus": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getStatsResponseByStatusItemCountMin)
})),
  "topRelations": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getStatsResponseTopRelationsItemRelationCountMin)
}))
})


export const getAnalyticsResponseTotalsEntitiesMin = 0;

export const getAnalyticsResponseTotalsRelationsMin = 0;

export const getAnalyticsResponseTotalsUnresolvedRelationsMin = 0;

export const getAnalyticsResponseTotalsDatedEntitiesMin = 0;

export const getAnalyticsResponseTotalsConnectedEntitiesMin = 0;

export const getAnalyticsResponseDistributionsByTypeItemCountMin = 0;

export const getAnalyticsResponseDistributionsByStatusItemCountMin = 0;

export const getAnalyticsResponseDistributionsByRelationFieldItemCountMin = 0;

export const getAnalyticsResponseDistributionsBySourceTargetTypeItemCountMin = 0;

export const getAnalyticsResponseCoverageItemCountMin = 0;

export const getAnalyticsResponseCoverageItemMissingMin = 0;

export const getAnalyticsResponseCoverageItemTotalMin = 0;

export const getAnalyticsResponseTimelineTotalDatedMin = 0;

export const getAnalyticsResponseTimelineYearsItemCountMin = 0;

export const getAnalyticsResponseTimelineYearsItemByTypeItemCountMin = 0;

export const getAnalyticsResponseTimelineYearsItemExamplesItemRelationCountMin = 0;

export const getAnalyticsResponseTimelineSeasonsItemCountMin = 0;

export const getAnalyticsResponseTimelineMonthsItemCountMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemEdgeCountMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemSourceCountMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemUniqueTargetsMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemResolvedTargetsMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemTopTargetsItemCountMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemTopTargetsItemSourceTypesItemCountMin = 0;

export const getAnalyticsResponseRelationsTopFieldsItemTopTargetsItemExamplesItemRelationCountMin = 0;

export const getAnalyticsResponseRelationsTopTargetsItemCountMin = 0;

export const getAnalyticsResponseRelationsTopTargetsItemSourceTypesItemCountMin = 0;

export const getAnalyticsResponseRelationsTopTargetsItemExamplesItemRelationCountMin = 0;

export const getAnalyticsResponseRelationsTopTargetsItemFieldsItemCountMin = 0;

export const getAnalyticsResponseRelationsUnresolvedCountMin = 0;

export const getAnalyticsResponseDataQualityMissingCoverItemRelationCountMin = 0;

export const getAnalyticsResponseDataQualityMissingExternalRefsItemRelationCountMin = 0;

export const getAnalyticsResponseDataQualityMissingSummaryItemRelationCountMin = 0;

export const getAnalyticsResponseDataQualityIsolatedItemRelationCountMin = 0;



export const GetAnalyticsResponse = zod.object({
  "generatedAt": zod.string(),
  "totals": zod.object({
  "entities": zod.number().min(getAnalyticsResponseTotalsEntitiesMin),
  "relations": zod.number().min(getAnalyticsResponseTotalsRelationsMin),
  "unresolvedRelations": zod.number().min(getAnalyticsResponseTotalsUnresolvedRelationsMin),
  "datedEntities": zod.number().min(getAnalyticsResponseTotalsDatedEntitiesMin),
  "connectedEntities": zod.number().min(getAnalyticsResponseTotalsConnectedEntitiesMin)
}),
  "distributions": zod.object({
  "byType": zod.array(zod.object({
  "id": zod.string(),
  "label": zod.string(),
  "count": zod.number().min(getAnalyticsResponseDistributionsByTypeItemCountMin)
})),
  "byStatus": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseDistributionsByStatusItemCountMin)
})),
  "byRelationField": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseDistributionsByRelationFieldItemCountMin)
})),
  "bySourceTargetType": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseDistributionsBySourceTargetTypeItemCountMin)
}))
}),
  "coverage": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseCoverageItemCountMin),
  "missing": zod.number().min(getAnalyticsResponseCoverageItemMissingMin),
  "total": zod.number().min(getAnalyticsResponseCoverageItemTotalMin),
  "percent": zod.number()
})),
  "timeline": zod.object({
  "totalDated": zod.number().min(getAnalyticsResponseTimelineTotalDatedMin),
  "years": zod.array(zod.object({
  "year": zod.number(),
  "count": zod.number().min(getAnalyticsResponseTimelineYearsItemCountMin),
  "byType": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseTimelineYearsItemByTypeItemCountMin)
})),
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseTimelineYearsItemExamplesItemRelationCountMin)
}))
})),
  "seasons": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseTimelineSeasonsItemCountMin)
})),
  "months": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseTimelineMonthsItemCountMin)
}))
}),
  "relations": zod.object({
  "topFields": zod.array(zod.object({
  "field": zod.string(),
  "edgeCount": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemEdgeCountMin),
  "sourceCount": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemSourceCountMin),
  "uniqueTargets": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemUniqueTargetsMin),
  "resolvedTargets": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemResolvedTargetsMin),
  "topTargets": zod.array(zod.object({
  "key": zod.string(),
  "targetTitle": zod.string(),
  "targetId": zod.string().nullish(),
  "targetType": zod.string().nullish(),
  "targetTypeLabel": zod.string().nullish(),
  "count": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemTopTargetsItemCountMin),
  "sourceTypes": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemTopTargetsItemSourceTypesItemCountMin)
})),
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseRelationsTopFieldsItemTopTargetsItemExamplesItemRelationCountMin)
}))
}))
})),
  "topTargets": zod.array(zod.object({
  "key": zod.string(),
  "targetTitle": zod.string(),
  "targetId": zod.string().nullish(),
  "targetType": zod.string().nullish(),
  "targetTypeLabel": zod.string().nullish(),
  "count": zod.number().min(getAnalyticsResponseRelationsTopTargetsItemCountMin),
  "sourceTypes": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseRelationsTopTargetsItemSourceTypesItemCountMin)
})),
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseRelationsTopTargetsItemExamplesItemRelationCountMin)
})),
  "fields": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getAnalyticsResponseRelationsTopTargetsItemFieldsItemCountMin)
}))
})),
  "unresolved": zod.object({
  "count": zod.number().min(getAnalyticsResponseRelationsUnresolvedCountMin),
  "examples": zod.array(zod.object({
  "sourceId": zod.string(),
  "targetId": zod.string().nullish(),
  "targetTitle": zod.string(),
  "targetType": zod.string().nullish(),
  "field": zod.string(),
  "direction": zod.enum(['out', 'in'])
}))
})
}),
  "dataQuality": zod.object({
  "missingCover": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseDataQualityMissingCoverItemRelationCountMin)
})),
  "missingExternalRefs": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseDataQualityMissingExternalRefsItemRelationCountMin)
})),
  "missingSummary": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseDataQualityMissingSummaryItemRelationCountMin)
})),
  "isolated": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getAnalyticsResponseDataQualityIsolatedItemRelationCountMin)
}))
})
})


export const GetCalendarQueryParams = zod.object({
  "year": zod.number().optional(),
  "month": zod.number().optional(),
  "type": zod.string().optional(),
  "source": zod.string().optional()
})

export const getCalendarResponseMonthMin = 0;

export const getCalendarResponseTotalsEntriesMin = 0;

export const getCalendarResponseTotalsTaxonomyMin = 0;

export const getCalendarResponseTotalsDailyNotesMin = 0;

export const getCalendarResponseTotalsDaysWithEntriesMin = 0;

export const getCalendarResponseDaysItemEntriesItemEntityRelationCountMin = 0;

export const getCalendarResponseDaysItemEntriesItemSnippetsItemLineMin = 0;

export const getCalendarResponseDaysItemCountsTotalMin = 0;

export const getCalendarResponseDaysItemCountsTaxonomyMin = 0;

export const getCalendarResponseDaysItemCountsDailyNotesMin = 0;



export const GetCalendarResponse = zod.object({
  "generatedAt": zod.string(),
  "year": zod.number(),
  "month": zod.number().min(getCalendarResponseMonthMin),
  "filters": zod.object({
  "type": zod.string().nullish(),
  "source": zod.string()
}),
  "totals": zod.object({
  "entries": zod.number().min(getCalendarResponseTotalsEntriesMin),
  "taxonomy": zod.number().min(getCalendarResponseTotalsTaxonomyMin),
  "dailyNotes": zod.number().min(getCalendarResponseTotalsDailyNotesMin),
  "daysWithEntries": zod.number().min(getCalendarResponseTotalsDaysWithEntriesMin)
}),
  "days": zod.array(zod.object({
  "date": zod.string(),
  "entries": zod.array(zod.object({
  "id": zod.string(),
  "date": zod.string(),
  "source": zod.enum(['taxonomy', 'daily-note']),
  "entity": zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getCalendarResponseDaysItemEntriesItemEntityRelationCountMin)
}),
  "dateField": zod.string().nullish(),
  "rawDate": zod.string().nullish(),
  "notePath": zod.string().nullish(),
  "snippets": zod.array(zod.object({
  "text": zod.string(),
  "heading": zod.string().nullish(),
  "line": zod.number().min(getCalendarResponseDaysItemEntriesItemSnippetsItemLineMin)
})).nullish()
})),
  "counts": zod.object({
  "total": zod.number().min(getCalendarResponseDaysItemCountsTotalMin),
  "taxonomy": zod.number().min(getCalendarResponseDaysItemCountsTaxonomyMin),
  "dailyNotes": zod.number().min(getCalendarResponseDaysItemCountsDailyNotesMin)
})
}))
})


export const GetEntitiesQueryParams = zod.object({
  "type": zod.string().optional(),
  "status": zod.string().optional(),
  "refs": zod.string().optional(),
  "cover": zod.string().optional(),
  "sort": zod.string().optional(),
  "direction": zod.string().optional(),
  "q": zod.string().optional(),
  "relation": zod.string().optional(),
  "pageSize": zod.number().optional(),
  "page": zod.number().optional()
})

export const getEntitiesResponseItemsItemRelationCountMin = 0;

export const getEntitiesResponseTotalMin = 0;



export const GetEntitiesResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getEntitiesResponseItemsItemRelationCountMin)
})),
  "total": zod.number().min(getEntitiesResponseTotalMin),
  "page": zod.number(),
  "pageSize": zod.number(),
  "totalPages": zod.number()
})


export const GetEntityDatesParams = zod.object({
  "id": zod.string()
})

export const getEntityDatesResponseTotalsMetadataMin = 0;

export const getEntityDatesResponseTotalsDailyNotesMin = 0;

export const getEntityDatesResponseTotalsSnippetsMin = 0;

export const getEntityDatesResponseDailyNotesItemSnippetsItemLineMin = 0;



export const GetEntityDatesResponse = zod.object({
  "generatedAt": zod.string(),
  "entityId": zod.string(),
  "totals": zod.object({
  "metadata": zod.number().min(getEntityDatesResponseTotalsMetadataMin),
  "dailyNotes": zod.number().min(getEntityDatesResponseTotalsDailyNotesMin),
  "snippets": zod.number().min(getEntityDatesResponseTotalsSnippetsMin)
}),
  "metadata": zod.array(zod.object({
  "id": zod.string(),
  "field": zod.string(),
  "value": zod.string(),
  "date": zod.string().nullish()
})),
  "dailyNotes": zod.array(zod.object({
  "id": zod.string(),
  "date": zod.string(),
  "notePath": zod.string(),
  "snippets": zod.array(zod.object({
  "text": zod.string(),
  "heading": zod.string().nullish(),
  "line": zod.number().min(getEntityDatesResponseDailyNotesItemSnippetsItemLineMin)
}))
}))
})


export const GetEntityParams = zod.object({
  "id": zod.string()
})

export const getEntityResponseEntityRelationCountMin = 0;



export const GetEntityResponse = zod.object({
  "entity": zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getEntityResponseEntityRelationCountMin),
  "frontmatter": zod.record(zod.string(), zod.unknown()),
  "body": zod.string(),
  "raw": zod.string()
}),
  "relations": zod.array(zod.object({
  "sourceId": zod.string(),
  "targetId": zod.string().nullish(),
  "targetTitle": zod.string(),
  "targetType": zod.string().nullish(),
  "field": zod.string(),
  "direction": zod.enum(['out', 'in'])
}))
})


export const GetRelationsQueryParams = zod.object({
  "sourceId": zod.string().optional(),
  "field": zod.string().optional()
})

export const getRelationsResponseTotalMin = 0;



export const GetRelationsResponse = zod.object({
  "items": zod.array(zod.object({
  "sourceId": zod.string(),
  "targetId": zod.string().nullish(),
  "targetTitle": zod.string(),
  "targetType": zod.string().nullish(),
  "field": zod.string(),
  "direction": zod.enum(['out', 'in'])
})),
  "total": zod.number().min(getRelationsResponseTotalMin)
})


export const getRelationGroupsResponseFieldsItemEdgeCountMin = 0;

export const getRelationGroupsResponseFieldsItemSourceCountMin = 0;

export const getRelationGroupsResponseFieldsItemUniqueTargetsMin = 0;

export const getRelationGroupsResponseFieldsItemResolvedTargetsMin = 0;

export const getRelationGroupsResponseFieldsItemTopTargetsItemCountMin = 0;

export const getRelationGroupsResponseFieldsItemTopTargetsItemSourceTypesItemCountMin = 0;

export const getRelationGroupsResponseFieldsItemTopTargetsItemExamplesItemRelationCountMin = 0;



export const GetRelationGroupsResponse = zod.object({
  "generatedAt": zod.string(),
  "fields": zod.array(zod.object({
  "field": zod.string(),
  "edgeCount": zod.number().min(getRelationGroupsResponseFieldsItemEdgeCountMin),
  "sourceCount": zod.number().min(getRelationGroupsResponseFieldsItemSourceCountMin),
  "uniqueTargets": zod.number().min(getRelationGroupsResponseFieldsItemUniqueTargetsMin),
  "resolvedTargets": zod.number().min(getRelationGroupsResponseFieldsItemResolvedTargetsMin),
  "topTargets": zod.array(zod.object({
  "key": zod.string(),
  "targetTitle": zod.string(),
  "targetId": zod.string().nullish(),
  "targetType": zod.string().nullish(),
  "targetTypeLabel": zod.string().nullish(),
  "count": zod.number().min(getRelationGroupsResponseFieldsItemTopTargetsItemCountMin),
  "sourceTypes": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getRelationGroupsResponseFieldsItemTopTargetsItemSourceTypesItemCountMin)
})),
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getRelationGroupsResponseFieldsItemTopTargetsItemExamplesItemRelationCountMin)
}))
}))
}))
})


export const GetRelationGroupParams = zod.object({
  "field": zod.string()
})

export const GetRelationGroupQueryParams = zod.object({
  "q": zod.string().optional(),
  "pageSize": zod.number().optional(),
  "page": zod.number().optional()
})

export const getRelationGroupResponseEdgeCountMin = 0;

export const getRelationGroupResponseUniqueTargetsMin = 0;

export const getRelationGroupResponseTargetsItemCountMin = 0;

export const getRelationGroupResponseTargetsItemSourceTypesItemCountMin = 0;

export const getRelationGroupResponseTargetsItemExamplesItemRelationCountMin = 0;

export const getRelationGroupResponseTotalMin = 0;



export const GetRelationGroupResponse = zod.object({
  "generatedAt": zod.string(),
  "field": zod.string(),
  "edgeCount": zod.number().min(getRelationGroupResponseEdgeCountMin),
  "uniqueTargets": zod.number().min(getRelationGroupResponseUniqueTargetsMin),
  "targets": zod.array(zod.object({
  "key": zod.string(),
  "targetTitle": zod.string(),
  "targetId": zod.string().nullish(),
  "targetType": zod.string().nullish(),
  "targetTypeLabel": zod.string().nullish(),
  "count": zod.number().min(getRelationGroupResponseTargetsItemCountMin),
  "sourceTypes": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getRelationGroupResponseTargetsItemSourceTypesItemCountMin)
})),
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getRelationGroupResponseTargetsItemExamplesItemRelationCountMin)
}))
})),
  "total": zod.number().min(getRelationGroupResponseTotalMin),
  "page": zod.number(),
  "pageSize": zod.number(),
  "totalPages": zod.number()
})


export const GetRelationTargetParams = zod.object({
  "field": zod.string(),
  "target": zod.string()
})

export const getRelationTargetResponseTargetCountMin = 0;

export const getRelationTargetResponseTargetSourceTypesItemCountMin = 0;

export const getRelationTargetResponseTargetExamplesItemRelationCountMin = 0;

export const getRelationTargetResponseGroupsItemCountMin = 0;

export const getRelationTargetResponseGroupsItemItemsItemRelationCountMin = 0;

export const getRelationTargetResponseTotalMin = 0;



export const GetRelationTargetResponse = zod.object({
  "generatedAt": zod.string(),
  "field": zod.string(),
  "target": zod.object({
  "key": zod.string(),
  "targetTitle": zod.string(),
  "targetId": zod.string().nullish(),
  "targetType": zod.string().nullish(),
  "targetTypeLabel": zod.string().nullish(),
  "count": zod.number().min(getRelationTargetResponseTargetCountMin),
  "sourceTypes": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number().min(getRelationTargetResponseTargetSourceTypesItemCountMin)
})),
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getRelationTargetResponseTargetExamplesItemRelationCountMin)
}))
}),
  "groups": zod.array(zod.object({
  "typeLabel": zod.string(),
  "count": zod.number().min(getRelationTargetResponseGroupsItemCountMin),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "typeLabel": zod.string(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "status": zod.string().nullish(),
  "dates": zod.array(zod.object({
  "field": zod.string(),
  "value": zod.string()
})),
  "image": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "path": zod.string(),
  "basename": zod.string(),
  "externalRefs": zod.record(zod.string(), zod.string()),
  "relationCount": zod.number().min(getRelationTargetResponseGroupsItemItemsItemRelationCountMin)
}))
})),
  "total": zod.number().min(getRelationTargetResponseTotalMin)
})
