import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One autogenerated sidebar over the whole content tree: page order comes from
// each page's `sidebar_position` front matter and each section's
// `_category_.json` (both carried over from the Zola `weight` values).
const sidebars: SidebarsConfig = {
  manual: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
